version: '3.8'
services:
  # CentOS 8 & Apache 2.4
  second_server:
    container_name: 'second_server'
    build: ./second_server
    ports:
      - '80:80'
    tty: true
    depends_on:
      - second_php
    restart: always
    privileged: true
    command: 
      - /sbin/init
    volumes:
      - ./second_src:/var/www/html
      - ./second_server/apache/logs:/var/log/httpd
      - ./second_server/apache/conf:/etc/httpd/conf.d
  
  # php(ComposerとNodeのコンテナでもある)
  second_php:
    container_name: 'second_php'
    build: ./second_php
    ports:
      - '9000'
    depends_on:
      - second_mysql
      - second_redis
      - second_mail
    restart: always
    tty: true
    volumes:
      - ./second_src:/var/www/html
  
  # MySQL
  second_mysql:
    container_name: 'second_mysql'
    build: ./second_mysql
    ports:
      - '13309:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: second_db
      MYSQL_USER: second_user
      MYSQL_PASSWORD: second
      TZ: 'Asia/Tokyo'
    volumes:
      - datastore:/var/lib/mysql
      - ./second_mysql/logs:/var/log/mysql

  # sfpt-server
  second_sftp:
    container_name: 'second_sftp'
    image: atmoz/sftp
    ports:
      - "2222:22"
    depends_on:
      - second_php
    command: second:second_pw:1001
    volumes:
      - ./second_sftp/upload:/home/second/upload
  
  # redis
  second_redis:
    container_name: 'second_redis'
    image: "redis:latest"
    ports: 
      - "6379:6379"
    volumes: 
      - "./second_redis:/data"
  
  # mail (hostへのmail送信設定がめんどくさいので、docker上だけでmail送信できるようにする)
  second_mail:
    container_name: second_mail
    image: mailhog/mailhog
    ports:
        - "8025:8025"
        - "1025:1025"

volumes:
  datastore: